package ARM;

import java.util.Arrays;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Daniel
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private EditableTableModel modelMemory;
    private EditableTableModel modelRegister;
    private boolean byteIsSelected;

    private Memory memory;
    private Register register;
    private ConditionFlags conditionFlag;
    private HashLabel hashLabel;

    public MainFrame() {
        initComponents();
        this.setResizable(false);
        this.memory = new Memory();
        this.register = new Register();
        this.hashLabel = new HashLabel();
        this.conditionFlag = new ConditionFlags();
        this.fillConditionalFlags();
    }

    public void fillConditionalFlags() {
        this.ZeroText.setText(this.conditionFlag.isZero() + "");
        this.NegativeText.setText(this.conditionFlag.isNegative() + "");
        this.CarryText.setText(this.conditionFlag.isCarry() + "");
        this.OverflowText.setText(this.conditionFlag.isoVerflow() + "");
    }

    public void fillRegisterTable() {

        String[] columnNames = {"R0", "R1", "R2", "R3", "R4", "R5", "R6", "R7",
            "R8", "R9", "R10", "R11", "R12", "R13", "R14", "R15"};

        Object[][] data = new Object[1][16];
        data[0][0] = this.register.getR0();
        data[0][1] = this.register.getR1();
        data[0][2] = this.register.getR2();
        data[0][3] = this.register.getR3();
        data[0][4] = this.register.getR4();
        data[0][5] = this.register.getR5();
        data[0][6] = this.register.getR6();
        data[0][7] = this.register.getR7();
        data[0][8] = this.register.getR8();
        data[0][9] = this.register.getR9();
        data[0][10] = this.register.getR10();
        data[0][11] = this.register.getR11();
        data[0][12] = this.register.getR12();
        data[0][13] = this.register.getR13();
        data[0][14] = this.register.getR14();
        data[0][15] = this.register.getR15();

        this.modelRegister = new EditableTableModel(data, columnNames);

        this.registerTable.setModel(this.modelRegister);

    }

    public void fillMemoryTable() {

        String[] columnNames = {"Position", "Data"};

        if (this.byteIsSelected) {
            Object[][] data = new Object[1024][2];
            for (int i = 0; i < this.memory.getSize(); i++) {

                data[i][0] = "0x" + this.memory.intToHex(i);
                data[i][1] = this.memory.loadByte(i);

            }
            this.modelMemory = new EditableTableModel(data, columnNames);
        } else {
            Object[][] data = new Object[256][2];
            for (int i = 0; i < this.memory.getSize(); i += 4) {

                data[i / 4][0] = "0x" + this.memory.intToHex(i);
                data[i / 4][1] = this.memory.loadWord(i);

            }
            this.modelMemory = new EditableTableModel(data, columnNames);
        }

        this.memoryTable.setModel(this.modelMemory);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMemory = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        memoryTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        registerTable = new javax.swing.JTable();
        runButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        radioButtonWords = new javax.swing.JRadioButton();
        radioButtonBytes = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        checkEdit = new javax.swing.JCheckBox();
        saveMemoryButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cleanMemoryButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        NegativeLabel = new javax.swing.JLabel();
        NegativeText = new javax.swing.JLabel();
        ZeroText = new javax.swing.JLabel();
        ZeroLabel = new javax.swing.JLabel();
        CarryLabel = new javax.swing.JLabel();
        CarryText = new javax.swing.JLabel();
        oVerflowLabel = new javax.swing.JLabel();
        OverflowText = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        codeText = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainPanel.setName("ARMSimulator"); // NOI18N

        memoryTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        memoryTable.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        memoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Position", "Data"
            }
        ));
        memoryTable.setFillsViewportHeight(true);
        memoryTable.setFocusable(false);
        memoryTable.setGridColor(java.awt.SystemColor.controlShadow);
        memoryTable.setRowHeight(24);
        memoryTable.setSelectionBackground(new java.awt.Color(102, 102, 102));
        memoryTable.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(memoryTable);

        registerTable.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        registerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "R0", "R1", "R2", "R3", "R4", "R5", "R6", "R7", "R8", "R9", "R10", "R11", "R12", "R13", "R14", "R15"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        registerTable.setFillsViewportHeight(true);
        registerTable.setFocusable(false);
        registerTable.setGridColor(java.awt.SystemColor.controlShadow);
        registerTable.setRowHeight(24);
        registerTable.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setViewportView(registerTable);
        if (registerTable.getColumnModel().getColumnCount() > 0) {
            registerTable.getColumnModel().getColumn(0).setResizable(false);
            registerTable.getColumnModel().getColumn(1).setResizable(false);
            registerTable.getColumnModel().getColumn(2).setResizable(false);
            registerTable.getColumnModel().getColumn(3).setResizable(false);
            registerTable.getColumnModel().getColumn(4).setResizable(false);
            registerTable.getColumnModel().getColumn(5).setResizable(false);
            registerTable.getColumnModel().getColumn(6).setResizable(false);
            registerTable.getColumnModel().getColumn(7).setResizable(false);
            registerTable.getColumnModel().getColumn(8).setResizable(false);
            registerTable.getColumnModel().getColumn(9).setResizable(false);
            registerTable.getColumnModel().getColumn(10).setResizable(false);
            registerTable.getColumnModel().getColumn(11).setResizable(false);
            registerTable.getColumnModel().getColumn(12).setResizable(false);
            registerTable.getColumnModel().getColumn(13).setResizable(false);
            registerTable.getColumnModel().getColumn(14).setResizable(false);
            registerTable.getColumnModel().getColumn(15).setResizable(false);
        }

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroupMemory.add(radioButtonWords);
        radioButtonWords.setText("Word");
        radioButtonWords.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonWordsItemStateChanged(evt);
            }
        });

        buttonGroupMemory.add(radioButtonBytes);
        radioButtonBytes.setText("Byte");
        radioButtonBytes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonBytesItemStateChanged(evt);
            }
        });

        jLabel1.setText("Data type:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radioButtonWords)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioButtonBytes))
                    .addComponent(jLabel1))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonWords)
                    .addComponent(radioButtonBytes))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        checkEdit.setText("Edit");
        checkEdit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkEditItemStateChanged(evt);
            }
        });

        saveMemoryButton.setText("Save");
        saveMemoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMemoryButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Memory");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(checkEdit)
                        .addGap(12, 12, 12)
                        .addComponent(saveMemoryButton))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveMemoryButton)
                    .addComponent(checkEdit)))
        );

        cleanMemoryButton.setText("Clean ");
        cleanMemoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanMemoryButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NegativeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NegativeLabel.setText("Negative:");

        NegativeText.setText("jLabel3");

        ZeroText.setText("jLabel3");

        ZeroLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ZeroLabel.setText("Zero:");

        CarryLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CarryLabel.setText("Carry:");

        CarryText.setText("jLabel3");

        oVerflowLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        oVerflowLabel.setText("oVerflow:");

        OverflowText.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NegativeLabel)
                .addGap(2, 2, 2)
                .addComponent(NegativeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ZeroLabel)
                .addGap(2, 2, 2)
                .addComponent(ZeroText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CarryLabel)
                .addGap(2, 2, 2)
                .addComponent(CarryText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oVerflowLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OverflowText))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(oVerflowLabel)
                        .addComponent(OverflowText))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CarryLabel)
                        .addComponent(CarryText))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ZeroLabel)
                        .addComponent(ZeroText))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NegativeLabel)
                        .addComponent(NegativeText)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(codeText);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(runButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cleanMemoryButton)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1373, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(runButton)
                                    .addComponent(cleanMemoryButton)))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(null);
        jMenuBar1.setFocusTraversalPolicy(null);
        jMenuBar1.setMaximumSize(new java.awt.Dimension(233, 32767));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(0, 0));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(233, 19));

        jMenu1.setText("File");

        jMenuItem1.setText("Generate Code");
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cleanMemoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanMemoryButtonActionPerformed
        this.memory.cleanMemory();
        this.register.cleanRegister();
        this.conditionFlag.cleanFlags();
        this.fillConditionalFlags();
        this.fillMemoryTable();
        this.fillRegisterTable();
    }//GEN-LAST:event_cleanMemoryButtonActionPerformed

    private void saveMemoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMemoryButtonActionPerformed
        if (this.byteIsSelected) {
            for (int count = 0; count < modelMemory.getRowCount(); count++) {
                String data = modelMemory.getValueAt(count, 1).toString();
                if (!"".equals(data)) {
                    this.memory.storeByte(count, data);
                }
            }
        } else {
            for (int count = 0; count < modelMemory.getRowCount(); count++) {
                String data = modelMemory.getValueAt(count, 1).toString();
                if (!"".equals(data)) {
                    this.memory.storeWord(count * 4, data);
                }

            }

        }

    }//GEN-LAST:event_saveMemoryButtonActionPerformed

    private void checkEditItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkEditItemStateChanged

        int column = 1; //Columna datos
        modelMemory.setColumnEditable(column, this.checkEdit.isSelected());
        this.memoryTable.setModel(modelMemory);

    }//GEN-LAST:event_checkEditItemStateChanged

    private void radioButtonBytesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButtonBytesItemStateChanged
        this.byteIsSelected = this.radioButtonBytes.isSelected();
        this.fillMemoryTable();
        this.checkEdit.setSelected(false);
    }//GEN-LAST:event_radioButtonBytesItemStateChanged

    private void radioButtonWordsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButtonWordsItemStateChanged

        this.fillMemoryTable();
        this.checkEdit.setSelected(false);
    }//GEN-LAST:event_radioButtonWordsItemStateChanged

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed

        this.register.cleanRegister();
        this.conditionFlag.cleanFlags();
        this.hashLabel.cleanHashLabel();
        Operation operation = new Operation(this.register, this.memory, this.conditionFlag, this.hashLabel);

 
                
        String[] lines = this.codeText.getText().split("\\n");
        
        WriteTxtFile file = new WriteTxtFile ();
        file.writeFile(lines);
        
        for (int i = operation.getPCCounter(); i < lines.length; i = operation.getPCCounter()) {
            //System.out.println(lines[i]);

            operation.selectOperation(lines[i]);
            this.fillConditionalFlags();
            this.fillMemoryTable();
            this.fillRegisterTable();
        }
     //   this.hashLabel.printHashLabel();

    }//GEN-LAST:event_runButtonActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    private class EditableTableModel extends DefaultTableModel {

        boolean[] columnEditable;

        public EditableTableModel(Object[][] data, String[] columnNames) {
            super(data, columnNames);
            columnEditable = new boolean[columnNames.length];
            Arrays.fill(columnEditable, false);
        }

        @Override
        public boolean isCellEditable(int row, int column) {
            if (!columnEditable[column]) {
                return false;
            } else {
                return super.isCellEditable(row, column);
            }
        }

        public void setColumnEditable(int column, boolean editable) {
            columnEditable[column] = editable;
        }

        public boolean getColumnEditable(int column) {
            return columnEditable[column];
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CarryLabel;
    private javax.swing.JLabel CarryText;
    private javax.swing.JLabel NegativeLabel;
    private javax.swing.JLabel NegativeText;
    private javax.swing.JLabel OverflowText;
    private javax.swing.JLabel ZeroLabel;
    private javax.swing.JLabel ZeroText;
    private javax.swing.ButtonGroup buttonGroupMemory;
    private javax.swing.JCheckBox checkEdit;
    private javax.swing.JButton cleanMemoryButton;
    private javax.swing.JTextPane codeText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable memoryTable;
    private javax.swing.JLabel oVerflowLabel;
    private javax.swing.JRadioButton radioButtonBytes;
    private javax.swing.JRadioButton radioButtonWords;
    private javax.swing.JTable registerTable;
    private javax.swing.JButton runButton;
    private javax.swing.JButton saveMemoryButton;
    // End of variables declaration//GEN-END:variables
}
