
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 21 17:29:06 CST 2016
//----------------------------------------------------

package ARM;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BLNE = 35;
  public static final int STR = 22;
  public static final int SBC = 8;
  public static final int LDR = 23;
  public static final int BNE = 32;
  public static final int PC = 44;
  public static final int MVN = 19;
  public static final int REGISTER = 40;
  public static final int ORR = 12;
  public static final int BLGT = 38;
  public static final int CMP = 10;
  public static final int CMN = 11;
  public static final int NEWINSTRUCTION = 49;
  public static final int BGT = 30;
  public static final int B = 26;
  public static final int AND = 2;
  public static final int LSL = 14;
  public static final int LR = 45;
  public static final int EOR = 3;
  public static final int BLGE = 36;
  public static final int MOV = 13;
  public static final int CORCHETEIZQUIERDO = 47;
  public static final int BGE = 27;
  public static final int EOF = 0;
  public static final int ASR = 15;
  public static final int error = 1;
  public static final int COMA = 46;
  public static final int MUL = 20;
  public static final int ADD = 6;
  public static final int ADC = 7;
  public static final int MLA = 21;
  public static final int BLLT = 37;
  public static final int BL = 33;
  public static final int BLT = 29;
  public static final int RSC = 9;
  public static final int CORCHETEDERECHO = 48;
  public static final int RSB = 5;
  public static final int BLLE = 39;
  public static final int HEXIMMEDIATE = 42;
  public static final int RRX = 16;
  public static final int BIC = 18;
  public static final int BLE = 28;
  public static final int DECIMALIMMEDIATE = 41;
  public static final int ROR = 17;
  public static final int LDRB = 25;
  public static final int STRB = 24;
  public static final int LABEL = 43;
  public static final int BLEQ = 34;
  public static final int SUB = 4;
  public static final int BEQ = 31;
}

